apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clients.tmax.io
  annotations:
    operator.version: 4.1.0.12
spec:
  group: tmax.io
  versions:
    - name: v1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: clients
    singular: client
    kind: Client
    shortNames:
    - client
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      required: [clientInfo]
      properties:
        clientInfo:
          type: object
          required: [appName, originUri, redirectUri, clientId, clientSecret]
          description: ClientInfo contains Client information
          properties:
            clientId:
              type: string
            clientSecret:
              type: string  
            appName:
              type: string
            originUri:
              type: string
            redirectUri:
              type: string
        status:
         type: object
         properties:
           lastTransitionTime:
             format: date-time
             type: string
           message:
             type: string
           reason:
             type: string
           status:
             type: string
             enum:
               - active
               - blockedr
  additionalPrinterColumns:
  - name: Status
    type: string
    JSONPath: .status.status
  subresources:
    status: {}