apiVersion: audit.k8s.io/v1 # This is required.
kind: Policy
omitStages:
  - "ResponseStarted"
  - "RequestReceived"
rules:

  # Don't log system requests.
  - level: None
    userGroups: ["system:serviceaccounts:hypercloud5-system", "system:nodes", "system:serviceaccounts", "system:masters"]
    
  # Don't log requests by hypercloud5-admin and kube-system user.
  - level: None
    users: ["system:serviceaccount:hypercloud5-system:hypercloud5-admin", "system:kube-controller-manager", "system:kube-scheduler", "system:apiserver"]
    
  # Don't log watch and get request
  - level: None
    verbs: ["watch", "get", "list"]
    
  # Log the request body of configmap changes in kube-system.
  - level: Metadata
    resources:
    # k8s resource
    - group: ""
    - group: "admissionregistration.k8s.io"
    - group: "apiextensions.k8s.io"
    - group: "apiregistration.k8s.io"
    - group: "apps"
    - group: "autoscaling"
    - group: "rbac.authorization.k8s.io"
    - group: "batch"
    - group: "servicecatalog.k8s.io"
    - group: "storage.k8s.io"
    - group: "policy"
    # storage
    - group: "ceph.rook.io"
    # istio
    - group: "authentication.istio.io"
    - group: "config.istio.io"
    - group: "networking.istio.io"
    - group: "rbac.istio.io"
    - group: "security.istio.io"
    # tmax.io
    - group: "tmax.io"
    - group: "claim.tmax.io"
    - group: "cluster.tmax.io"
    - group: "console.tmax.io"
    - group: "cicd.tmax.io"
    - group: "cicdapi.tmax.io"
    - group: "helmapi.tmax.io"
    # cicd
    - group: "tekton.dev"
    - group: "triggers.tekton.dev"
    # multi cluster
    - group: "types.kubefed.io"
    - group: "core.kubefed.io"
    - group: "cluster.x-k8s.io"
    - group: "addons.cluster.x-k8s.io"
    - group: "exp.cluster.x-k8s.io"
    - group: "bootstrap.cluster.x-k8s.io"
    - group: "controlplane.cluster.x-k8s.io"
    - group: "infrastructure.cluster.x-k8s.io"
    - group: "multiclusterdns.kubefed.io"
    - group: "scheduling.kubefed.io"
    # hyperframe
    - group: "kafka.strimzi.io"
    - group: "redis.redis.opstreelabs.in"
    # ML
    - group: "kubeflow.org"
    - group: "serving.kubeflow.org"
    # etc
    - group: "binding.operators.coreos.com"
  
  # Don't log others.
  - level: None
