apiVersion: v1
kind: Service
metadata:
  name: console
  namespace: console-system
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 80 
    targetPort: 8080
  selector:
    app: console   
    hypercloud: ui
