apiVersion: v1
kind: Service
metadata:
  name: console-np
  namespace: console-system
spec:
  type: NodePort
  ports:
  - name: "https"
    port: 443
    targetPort: 8443
    nodePort: 31443
  - name: "http"
    port: 80 
    targetPort: 8080
    nodePort: 31080
  selector:
    app: console   
    hypercloud: ui
