apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  namespace: console-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
      hypercloud: ui
  template:
    metadata:
      labels:
        app: console
        hypercloud: ui
      name: hypercloud-ui
    spec:
      containers:
        - command:
            - /opt/bridge/bin/console
            - server
            - --public-dir=/opt/bridge/static
            - --servingInfo.listen=http://0.0.0.0:8080
            - --servingInfo.baseAddress=http://0.0.0.0:8080
            - --app.keycloakRealm=@@REALM@@
            - --app.keycloakAuthUrl=https://@@KEYCLOAK@@/auth
            - --app.keycloakClientId=@@CLIENTID@@
            - --app.mcMode=@@MC_MODE@@
          image: tmaxcloudck/hypercloud-console:@@CONSOLE_VER@@
          imagePullPolicy: Always
          name: console
          ports:
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File