apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-user
  labels:
    purpose: namespace-user
    madeby: tmax
rules:
- apiGroups: ['']
  resources: ['*']
  verbs: ['*']
- apiGroups: ['events.k8s.io']
  resources: ['*']
  verbs: ['*']
- apiGroups: ['servicecatalog.k8s.io']
  resources: ['*']
  verbs: ['*']
- apiGroups: ['apps']
  resources: ['*']
  verbs: ['*']
- apiGroups: ['autoscaling']
  resources: ['*']
  verbs: ['*']
- apiGroups: ['batch']
  resources: ['*']
  verbs: ['*']
- apiGroups: ['extensions']
  resources: ['*']
  verbs: ['*']
- apiGroups: ['networking.k8s.io']
  resources: ['*']
  verbs: ['*']
- apiGroups: ['networking.istio.io']
  resources: ['*']
  verbs: ['*']
- apiGroups: ['snapshot.storage.k8s.io']
  resources: ['*']
  verbs: ['*']
- apiGroups: ['storage.k8s.io']
  resources: ['*']
  verbs: ['*']
- apiGroups: ['tekton.dev']
  resources: ['*']
  verbs: ['*']
- apiGroups: ['policy']
  resources: ['*']
  verbs: ['*']
- apiGroups: ['apiextensions.k8s.io']
  resources: ['*']
  verbs: ['*']
- apiGroups: ['tmax.io']
  resources: ['template','templateinstances','registries','namespaceclaims','users']
  verbs: ['*']
